plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

// lombok은 Maven 레포지토리에서 가져오기 때문에 build.gradle에 아래 구문을 추가
repositories {
	mavenCentral()
}

dependencies {
	// Web & Thymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// devTools
	// 파일 수정 시 재시작하지 않고 자동 컴파일 될 수 있도록 하기위한 라이브러리
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Jpa & DB
	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	//MySql
	implementation 'org.mariadb.jdbc:mariadb-java-client'
	runtimeOnly 'com.mysql:mysql-connector-j'
	runtimeOnly 'com.h2database:h2' // 개발용 인메모리 DB

	//QueryDSL 추가
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	// Security & OAuth2
	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	testImplementation 'org.springframework.security:spring-security-test'
	implementation 'org.springframework.security:spring-security-crypto:5.7.1'

	// jwt 패키지
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// 이메일
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	// 웹소켓을 사용하기 위한 라이브러리
	implementation 'org.springframework.boot:spring-boot-starter-websocket:3.3.2'

	// 유효성 검증 (Validation)
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// 문서화 (Swagger / openAPI)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'

	// lombok
	// DTO 어노테이션을 줄이기 위한 롬복 라이브러리
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

tasks.named('test') {
	useJUnitPlatform()
}
