spring.application.name=reactdemo

server.port=8080

server.servlet.context-path=/

# MySQL
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# DB Source URL
spring.datasource.url=jdbc:mariadb://localhost:3307/rotse?allowPublicKeyRetrieval=true&useSSL=false
# DB username
spring.datasource.username=rotse
# DB password
spring.datasource.password=9661

## JPA 설정
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect



#
spring.thymeleaf.cache=false

### security user 7
## 한국어 입력
spring.security.user.name=user
spring.security.user.password=1111

## OSIV 측면에서 매우 부적절
## 성능이나 scalability,, 즉 확장성 측면에서 볼 때 false로 해야 하는데 true로 하고 있어 warning
spring.jpa.open-in-view=false

## 세션 소멸 시간 설정
server.servlet.session.timeout=30m

server.servlet.session.tracking-modes = cookie

## jwt Secret Key
jwt.secret=

# 24시간 (밀리초)
app.jwt.expiration-in-ms=

## Redis 설정
spring.redis.host=localhost
spring.redis.port=6379

## 구글 SMTP 설정 (예시 : gmail)
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true